# Generated by Django 5.2 on 2025-04-22 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id_design', models.AutoField(primary_key=True, serialize=False)),
                ('design_name', models.CharField(blank=True, max_length=45, null=True)),
                ('pdb_id', models.CharField(blank=True, max_length=45, null=True)),
                ('ref_link', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'design',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id_protocol', models.AutoField(primary_key=True, serialize=False)),
                ('protocol_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'protocol',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id_unit', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='SpecificProperty',
            fields=[
                ('id_sp', models.AutoField(primary_key=True, serialize=False)),
                ('sp_name', models.CharField(blank=True, max_length=45, null=True)),
                ('fk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein_design.category')),
            ],
            options={
                'db_table': 'specific_property',
                'unique_together': {('id_sp', 'fk_category')},
            },
        ),
        migrations.CreateModel(
            name='UsedTechnique',
            fields=[
                ('id_techniques', models.AutoField(primary_key=True, serialize=False)),
                ('technique_name', models.CharField(blank=True, max_length=45, null=True)),
                ('technique_type', models.CharField(blank=True, choices=[('experimental', 'Experimental'), ('computational', 'Computational')], max_length=15, null=True)),
                ('ref_doc', models.CharField(blank=True, max_length=45, null=True)),
                ('fk_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein_design.design')),
            ],
            options={
                'db_table': 'used_techniques',
                'unique_together': {('id_techniques', 'fk_design')},
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id_sequences', models.AutoField(primary_key=True, serialize=False)),
                ('chain_id', models.CharField(blank=True, max_length=45, null=True)),
                ('sequence', models.TextField(blank=True, null=True)),
                ('length', models.CharField(blank=True, max_length=45, null=True)),
                ('fk_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein_design.design')),
            ],
            options={
                'db_table': 'sequences',
                'unique_together': {('id_sequences', 'fk_design')},
            },
        ),
        migrations.CreateModel(
            name='UnitHasSpecificProperty',
            fields=[
                ('id_unit_sp', models.AutoField(primary_key=True, serialize=False)),
                ('fk_sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein_design.specificproperty')),
                ('fk_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein_design.unit')),
            ],
            options={
                'db_table': 'unit_has_specific_property',
                'unique_together': {('fk_unit', 'fk_sp')},
            },
        ),
        migrations.CreateModel(
            name='ExperimentalResult',
            fields=[
                ('id_experimental_results', models.AutoField(primary_key=True, serialize=False)),
                ('result_file', models.BinaryField(blank=True, null=True)),
                ('fk_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein_design.design')),
                ('fk_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein_design.usedtechnique')),
            ],
            options={
                'db_table': 'experimental_results',
                'unique_together': {('id_experimental_results', 'fk_technique', 'fk_design')},
            },
        ),
        migrations.CreateModel(
            name='ComputationalResult',
            fields=[
                ('id_computational_results', models.AutoField(primary_key=True, serialize=False)),
                ('result_file', models.BinaryField(blank=True, null=True)),
                ('fk_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein_design.design')),
                ('fk_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein_design.usedtechnique')),
            ],
            options={
                'db_table': 'computational_results',
                'unique_together': {('id_computational_results', 'fk_technique', 'fk_design')},
            },
        ),
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id_assays', models.AutoField(primary_key=True, serialize=False)),
                ('assay_name', models.CharField(blank=True, max_length=45, null=True)),
                ('success_validation', models.BooleanField(blank=True, null=True)),
                ('fk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein_design.category')),
                ('fk_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein_design.design')),
                ('fk_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein_design.protocol')),
                ('fk_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein_design.usedtechnique')),
            ],
            options={
                'db_table': 'assays',
                'unique_together': {('id_assays', 'fk_protocol', 'fk_category', 'fk_design', 'fk_technique')},
            },
        ),
    ]
