# Generated by Django 5.2 on 2025-05-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein_design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='organism',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
