# Generated by Django 5.2 on 2025-05-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein_design', '0003_computationalresult_result_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='design_type',
            field=models.CharField(blank=True, choices=[('De Novo Design', 'de novo design'), ('Protein Engineering', 'protein engineering')], max_length=45, null=True),
        ),
    ]
