# Generated by Django 5.2 on 2025-06-01 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein_design', '0003_specificproperty_unithasspecificproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignHasSpecificProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_design', models.ForeignKey(db_column='fk_id_design', on_delete=django.db.models.deletion.CASCADE, to='protein_design.design')),
                ('fk_id_sp', models.ForeignKey(db_column='fk_id_sp', on_delete=django.db.models.deletion.CASCADE, to='protein_design.specificproperty')),
            ],
            options={
                'db_table': 'design_has_specific_property',
                'unique_together': {('fk_id_design', 'fk_id_sp')},
            },
        ),
    ]
