# Generated by Django 5.2 on 2025-05-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein_design', '0004_design_design_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedtechnique',
            name='technique_name',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
