# Generated by Django 5.2 on 2025-05-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein_design', '0005_alter_usedtechnique_technique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='specificproperty',
            name='sp_name',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
