# Generated by Django 5.2 on 2025-05-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein_design', '0006_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='usedtechnique',
            name='technique_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
